title: L-g Chimio
lang : fr-FR
show_downloads : true
github :
   zip_url : https://github.com/JordiMa/L-g-Chimio-release/archive/v1.5.zip
   tar_url : https://github.com/JordiMa/L-g-Chimio-release/archive/v1.5.tar.gz
theme: jekyll-theme-cayman