<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jordi
 * Date: Tue, 23 Apr 2019 15:01:06 +0200
 */

$conf['title'] = 'L-g Chimio';
$conf['lang'] = 'fr';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['passcrypt'] = 'bcrypt';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,index,recent,revisions,register,source,export_raw';

// end auto-generated content
