<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Thu, 06 Dec 2018 08:41:31 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
